export class Departments {
    departmentId: number; // Optional, as it is usually generated by the database
    departmentName: string;
    departmentDesc: string;

    constructor(
        departmentId: number,
        departmentName: string,
        departmentDesc: string,
    ){
        this.departmentId = departmentId;
        this.departmentName = departmentName;
        this.departmentDesc = departmentDesc;
    }
}