export class Employees {
  employeeId: number; // Optional, as it is usually generated by the database
  firstName: string;
  middleName: string;
  lastName: string;
  salary: number;
  email: string;
  mobile: number;
  departmentId: number;
  roleId: number;
  status: string;
  employeeCode: string;
  hireDate: string; // Use ISO date string format for LocalDate
  departmentName: string;
  roleName: string;
  valueCode:string;
  valueName:string;

  constructor(
    employeeId: number,
    firstName: string,
    middleName: string,
    lastName: string,
    salary: number,
    email: string,
    mobile: number,
    departmentId: number,
    roleId: number,
    status: string,
    employeeCode: string,
    hireDate: string,
    departmentName: string,
    roleName: string,
    valueCode:string,
    valueName:string
  ) {
    this.employeeId = employeeId;
    this.firstName = firstName;
    this.middleName = middleName;
    this.lastName = lastName;
    this.salary = salary;
    this.email = email;
    this.mobile = mobile;
    this.departmentId = departmentId;
    this.roleId = roleId;
    this.status = status;
    this.employeeCode = employeeCode;
    this.hireDate = hireDate;
    this.departmentName = departmentName;
    this.roleName = roleName;
    this.valueCode = valueCode;
    this.valueName = valueName;
  }
}
