export class Roles {
    roleId: number; // Optional, as it is usually generated by the database
    roleName: string;
    roleDesc: string;

    constructor(
        roleId: number,
        roleName: string,
        roleDesc: string,
    ){
        this.roleId = roleId;
        this.roleName = roleName;
        this.roleDesc = roleDesc;
    }
}